- name: "Download docker"
  shell: |
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh

- name: "Run jenkins"
  shell: |
    mkdir -p /root/jenkins_home
    sudo chown -R 1000 /root/jenkins_home
    docker run -d -p 8080:8080 -p 50000:50000 -v /root/jenkins_home:/var/jenkins_home jenkins/jenkins
  register: debug_output

- debug: msg="{{ debug_output.stdout }}"

- debug: msg="{{ debug_output.stderr }}"