- name: "update apt packages."
  apt:
    update_cache: yes

- name: "upgrade packages"
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: install node
  shell: |
    curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash - && sudo apt-get install -y nodejs

- name: "Install java"
  shell: |
    yes | sudo apt install default-jre
    yes | sudo apt install default-jdk

- name: "Install jenkins"
  shell: |
    wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
    sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
    sudo apt update
    yes | sudo apt install jenkins

- name: "Start jenkins"
  shell: |
    sudo systemctl start jenkins

- name: "Download docker"
  shell: |
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
    sudo usermod -aG docker jenkins
    sudo usermod -aG docker ubuntu