- name: "update apt packages."
  apt:
    update_cache: yes

- name: "upgrade packages"
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: "Install zip utility."
  apt:
    name: [ "zip", "unzip" ]
    state: latest
    update_cache: yes

- name: install node
  shell: |
    curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash - && sudo apt-get install -y nodejs

- name: install awscli
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install

- name: install hadolint
  shell: |
    wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
    chmod +x /bin/hadolint

- name: "Install java"
  shell: |
    yes | sudo apt install default-jre
    yes | sudo apt install default-jdk

- name: "Install jenkins"
  shell: |
    wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
    sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
    sudo apt update
    yes | sudo apt install jenkins

- name: "Start jenkins"
  shell: |
    sudo systemctl start jenkins

- name: "Install pass to save docker credentials"
  shell: |
    yes | sudo apt-get install pass

- name: "Download docker"
  shell: |
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
    sudo usermod -aG docker jenkins
    sudo usermod -aG docker ubuntu

- name: "Docker login"
  shell: |
    docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

- name: "Download k8"
  shell: |
    sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2 curl
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
    echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
    sudo apt-get update
    sudo apt-get install -y kubectl

- name: "Install minikube"
  shell: |
    curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
      && chmod +x minikube
    sudo cp minikube /usr/local/bin && rm minikube

- name: "Start minikube"
  become: false # because the docker driver should not be used with root privileges
  shell: |
    minikube start --driver=docker

- name: "Configure kubectl for Amazon EKS cluster"
  shell: |
    aws eks update-kubeconfig --name udacity-project-capstone

