apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-project-capstone-deployment
  labels:
    app: udacity-project-capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacity-project-capstone
  template:
    metadata:
      labels:
        app: udacity-project-capstone
    spec:
      containers:
        - name: laravel-app
          image: bendaniel10/udacity-project-capstone:prod
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: udacity-project-capstone-service
spec:
  selector:
    app: udacity-project-capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer